### ISSUE TITLE
"RMS service is disabled for publishing for this user."

### ISSUE THREAD

**Issue by catmanjan** [MicrosoftDocs/Azure-RMSDocs#1359] opened 2021-04-29 04:43 UTC
I receive the following error on this line:

``` Task.Run(async () => await fileHandler.CommitAsync(protectedFilePath)).Result;```

"RMS service is disabled for publishing for this user."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11607740-b4f9-c134-3094-95f2d7d389fa
* Version Independent ID: 196fbda6-5079-d3f0-f02e-7e29531e8dc5
* Content: [How to - Republishing scenario C#](https://docs.microsoft.com/en-us/information-protection/develop/quick-file-republishing-csharp)
* Content Source: [mip/develop/quick-file-republishing-csharp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/quick-file-republishing-csharp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment] 2021-05-03 10:59
Hi @catmanjan, thanks for your feedback on our docs!
@tommoser might be able to helo you here - otherwise, you might want to open a support ticket.
You can find information about support options for AIP on this page in our docs.
https://docs.microsoft.com/en-us/azure/information-protection/information-support

**Comment by tommoser** [comment] 2021-05-05 22:30
This is likely caused by the user missing from the onboarding policy controls. You'll need to be in the correct group, licensed for the service, or both depending on the config.

https://docs.microsoft.com/en-us/powershell/module/aadrm/set-aadrmonboardingcontrolpolicy?view=azureipps

**Comment by batamig** [comment] 2021-05-06 07:29
Thanks @tommoser! @catmanjan , I'm going to close this issue for now, but feel free to add more feedback as needed.
#please-close

**Closed by batamig** 2021-05-06 07:29 UTC
Labels: Pri2, information-protection/svc
