### ISSUE TITLE
How to color the labels

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/Azure-RMSDocs#817] opened 2019-03-13 11:46 UTC
In latest preview release notes, its mentioned that colors for the labels is supported. But how to configure the colors and where? I checked in SCC, there is no settings for labels under Classification, so wondering where to configure it?

**Comment by cabailey** [comment] 2019-03-13 18:03
Duplicate of https://github.com/MicrosoftDocs/Azure-RMSDocs/issues/818 
#please-close

**Closed** 2019-04-02 21:38 UTC
