### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by cfoulon** [MicrosoftDocs/Azure-RMSDocs#924] opened 2019-06-21 13:22 UTC
Any updates on its functionality for MacOS clients?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c744cf2-5e29-11c4-8e30-9af0adfaa8da
* Version Independent ID: 708c51d5-946a-c162-fcdc-7a4e309ba855
* Content: [Azure Information Protection client - Install & configure](https://docs.microsoft.com/en-us/azure/information-protection/configure-client#feedback)
* Content Source: [Azure-RMSDocs/configure-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-client.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment] 2019-06-25 16:02
This seems to be a duplicate of https://github.com/MicrosoftDocs/Azure-RMSDocs/issues/925 where answered there.
#please-close

**Closed by cabailey** 2019-06-25 16:02 UTC
Labels: information-protection/svc
