### ISSUE TITLE
include known issues where data is not collected

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/Azure-RMSDocs#990] opened 2019-08-21 10:25 UTC
include known issues / caveats where data is not collected.

ie if content is accessed by a client and the content is stored in ODFB or SPO & RunPolicyinBackground is enabled - AIP Clients will not send matched content to logging to support analytics (reporting, misuse, falsepos support)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b75d85e-3cea-279c-feaf-c8f828f3d201
* Version Independent ID: 97d9a1b1-4db3-a1c0-69fe-8032ce615fc7
* Content: [Central reporting for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/reports-aip)
* Content Source: [Azure-RMSDocs/reports-aip.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/reports-aip.md)
* Service: **information-protection**
* Sub-service: **analytics**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment] 2019-08-21 19:39
@bakerm00  I'm not aware of this limitation - is this confirmed by Microsoft support?  Sending matched content uses endpoint discovery, which for the client, runs when a file is first saved and not each time AutoSave runs in SharePoint.  Can you confirm that the matched content isn't sent when a file is first saved?

**Comment by bakerm00** [comment] 2019-08-21 21:24
119081422001658

Mike Baker
Infrastructure Architect
Elsevier
+44(0)7747020245
________________________________

**Comment by cabailey** [comment] 2019-08-23 16:36
@bakerm00  It seems this is an ongoing support issue with nothing confirmed yet to be missing or incorrect from the documentation.  Uwe said he'll update me if there is anything to add to the docs.

Since there is nothing actionable for the docs at this time, I'll close this issue & progress through the support ticket so we have a single source of information.
#please -close

**Comment by cabailey** [comment] 2019-08-23 16:38
#please-close

**Closed by cabailey** 2019-08-23 16:38 UTC
Labels: Pri1, analytics/subsvc, information-protection/svc
