### ISSUE TITLE
Importing label language translations - language changes over time

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/Azure-RMSDocs#836] opened 2019-03-22 13:19 UTC
It isn't clear in the documentation if importing label translations in one language can be done independently of importing translations for others.  For example, if a translation for Polish is made on Monday and imported and then a translation is made for Finnish on Tuesday will importing the Finnish translation cause the Polish translation to be removed ?  If it is removed, then the import on Tuesday must include both the Polish and Finnish translations _AND_ any other language translations done previously.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58bf4357-5354-9750-bee2-3204f85b5743
* Version Independent ID: 82dd2f29-441d-0d9b-3bd4-7d056981017a
* Content: [Configure labels and templates for different languages in Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-languages)
* Content Source: [Azure-RMSDocs/configure-policy-languages.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-languages.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment] 2019-03-26 00:41
@bholzmmc Since each language has its own xml file, I don't think it matters if you upload the files independently at different times, but I'll check.

**Comment by cabailey** [comment] 2019-04-02 19:58
Now confirmed & I've updated the page. Because each language has its own file, you can upload them separately. For example, you select Polish and Finnish.  The zip file you download has an .xlm file for each language. If you complete the translations for Polish but not Finnish, you can upload just the .xlm file for Polish in a zip file.  When you complete your translations for Finnish, upload that .xlm file in another zip file.  

The xlm files contain the complete language strings for a single language so if you make updates, it's a good idea to always download the xlm file again, just in case your locally saved version (previously downloaded) is different.

**Comment by cabailey** [comment] 2019-04-13 02:10
Hi again @bholzmmc  I think your issue is resolved now - OK to close this?

**Closed** 2019-04-15 13:02 UTC
Labels: information-protection/svc
